[FIX] returns the default team as a browsed record instead of the internal id. Otherwise error occurs as "AttributeError: 'int' object has no attribute 'id'"